quasar:
  container_name: "teste_name"
  build: .
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - .:/home/FormsCovid
  command: "quasar dev -m pwa"
  environment:
    - CHOKIDAR_USEPOLLING=true #variavel para permitir o hot-reloading